/*Un cursor que muestre la cantidad de niños que emigraron en determinado año*/

DO $$
DECLARE
	CANTIDAD INT:= 0;
	AÑO INT := 2021;
	EDAD RECORD;
	CURSOR_EDAD CURSOR FOR 
	SELECT CLIENTE_FECHA_NACIMIENTO FROM CLIENTE;
BEGIN
	OPEN CURSOR_EDAD;
	FETCH CURSOR_EDAD 	 INTO EDAD;
	WHILE (FOUND) LOOP
	IF (AÑO - EXTRACT (YEAR FROM EDAD.CLIENTE_FECHA_NACIMIENTO))<18 then
	CANTIDAD := CANTIDAD + 1; 

	end if;
	FETCH CURSOR_EDAD 	 INTO EDAD;
END LOOP;
RAISE NOTICE 'CANTIDAD DE NIÑOS QUE INGRESARON en el año % ==>% ',AÑO,cantidad;
END $$
LANGUAGE 'plpgsql';